import type { Category, Product, DeliveryZone } from './types';
import { expandedProducts } from './fixture-expansion.ts';

export const categories: Category[] = [
  'Dresses',
  'Tops',
  'Shirts',
  'Trousers',
  'Sets',
  'Shoes',
  'Bags',
  'Jewellery',
  'Accessories',
  'Kids clothing',
  'Skirts',
  'Shorts',
].map((name, i) => ({
  id: `10000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`,
  name,
  slug: name.toLowerCase().replaceAll(' ', '-'),
  parent_id: null,
  position: i,
  active: true,
}));
const catalogue = [
  [
    'The Sade midi dress',
    'sade-midi-dress',
    'Dresses',
    'women',
    38500,
    'dress',
    'Sand',
    ['S', 'M', 'L', 'XL'],
  ],
  [
    'The everyday linen shirt',
    'everyday-linen-shirt',
    'Shirts',
    'men',
    28500,
    'shirt',
    'Stone',
    ['S', 'M', 'L', 'XL'],
  ],
  [
    'The sculptural drop earrings',
    'sculptural-drop-earrings',
    'Jewellery',
    'women',
    12500,
    'earrings',
    'Gold',
    ['One size'],
  ],
  ['The everyday carry', 'everyday-carry', 'Bags', 'women', 32000, 'bag', 'Ivory', ['One size']],
  [
    'The after-hours set',
    'after-hours-set',
    'Sets',
    'women',
    46500,
    'campaign',
    'Ink',
    ['S', 'M', 'L'],
  ],
  [
    'The woven weekend sandals',
    'woven-weekend-sandals',
    'Shoes',
    'women',
    18500,
    'sandals',
    'Natural',
    ['36', '37', '38', '39', '40', '41'],
  ],
  [
    'The little day dress',
    'little-day-dress',
    'Kids clothing',
    'girls',
    16500,
    'kids',
    'Oat',
    ['2–3 years', '4–5 years', '6–7 years'],
  ],
  [
    'The little explorer knit',
    'little-explorer-knit',
    'Kids clothing',
    'boys',
    15500,
    'baby',
    'Oat',
    ['1–2 years', '2–3 years', '3–4 years'],
  ],
  [
    'The Sunday column dress',
    'sunday-column-dress',
    'Dresses',
    'women',
    42000,
    'studio',
    'Ivory',
    ['S', 'M', 'L'],
  ],
  [
    'The relaxed overshirt',
    'relaxed-overshirt',
    'Shirts',
    'men',
    34500,
    'shirt',
    'Grey',
    ['S', 'M', 'L'],
  ],
  [
    'The small shoulder bag',
    'small-shoulder-bag',
    'Accessories',
    'women',
    24500,
    'bag',
    'Ivory',
    ['One size'],
  ],
  [
    'The first-days cardigan',
    'first-days-cardigan',
    'Kids clothing',
    'babies',
    12500,
    'baby',
    'Cream',
    ['0–3 months', '3–6 months', '6–12 months'],
  ],
] as const;
const additionalColours: Record<string, { name: string; image: string }[]> = {
  'sculptural-drop-earrings': [{ name: 'Silver', image: '/images/earrings-silver.webp' }],
  'everyday-linen-shirt': [
    { name: 'Sage', image: '/images/shirt-sage.webp' },
    { name: 'Dusty blue', image: '/images/shirt-dusty-blue.webp' },
  ],
  'everyday-carry': [
    { name: 'Cocoa', image: '/images/bag-cocoa.webp' },
    { name: 'Oxblood', image: '/images/bag-oxblood.webp' },
  ],
};
export const products: Product[] = [
  ...catalogue.map((p, i) => ({
    id: `20000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`,
    name: p[0],
    slug: p[1],
    category: p[2],
    audience: p[3],
    price: p[4] * 100,
    compare_at: null,
    images: [`/images/${p[5]}.jpg`, ...(additionalColours[p[1]] || []).map((c) => c.image)],
    alt: `Style photograph for ${p[0].toLowerCase()}`,
    short_description: 'An easy addition to your everyday rotation.',
    description:
      'A considered silhouette with room to make it your own. Pair with pieces you already love, for slow weekends, busy mornings and everything in between.',
    status: 'active' as const,
    tags: ['new-in', 'everyday', ...(i < 6 ? ['the-everyday-edit'] : [])],
    featured: i < 4,
    fixture: true,
    details: ['Easy everyday fit', 'See size options for this individual style'],
    care: 'Follow the garment care label.',
    created_at: `2026-10-${String(Math.max(1, 2 - Math.floor(i / 6))).padStart(2, '0')}T00:00:00Z`,
    variants: [
      ...p[7].map((size, j) => ({
        id: `30000000-0000-4000-8000-${String(i * 10 + j + 1).padStart(12, '0')}`,
        sku: `DEV-ORE-${i + 1}-${j + 1}`,
        attributes: { Colour: p[6], Size: size },
        price: null,
        image: `/images/${p[5]}.jpg`,
        stock: i === 0 && j === 3 ? 0 : 7 + j,
      })),
      ...(additionalColours[p[1]] || []).flatMap((colour, c) =>
        p[7].map((size, j) => ({
          id: `31000000-0000-4000-8000-${String(i * 100 + c * 10 + j + 1).padStart(12, '0')}`,
          sku: `DEV-ORE-${i + 1}-C${c + 1}-${j + 1}`,
          attributes: { Colour: colour.name, Size: size },
          price: null,
          image: colour.image,
          stock: 5 + j,
        })),
      ),
    ],
  })),
  ...expandedProducts,
];
export const deliveryZones: DeliveryZone[] = [
  {
    id: '40000000-0000-4000-8000-000000000001',
    name: 'Lagos',
    states: ['Lagos'],
    rate: 250000,
    free_threshold: null,
    min_days: 2,
    max_days: 4,
    active: true,
    fixture: true,
  },
  {
    id: '40000000-0000-4000-8000-000000000002',
    name: 'FCT',
    states: ['FCT'],
    rate: 450000,
    free_threshold: null,
    min_days: 3,
    max_days: 6,
    active: true,
    fixture: true,
  },
];
